# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  - 7.1
  - 7.2
  # aliased to a recent hhvm version
  - hhvm

# needed to start a webserver?
sudo: true

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# optionally set up exclusions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.2
#    - php: hhvm

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS lawnlove_crm_test;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'notroot'@'localhost' IDENTIFIED BY 'localhostpass';" -uroot; fi
#start webserver
  - php -S 127.0.0.1:8000 > /dev/null &
  - sleep 1
  - chromedriver --url-base=/wd/hub
  - sleep 3


install:
  - composer install
# use the $DB env variable to determine the phpunit.xml to use
script:
  - phpunit --configuration phpunit_$DB.xml --coverage-text --verbose
  # execute codeception tests
  - php vendor/codeception/codeception/codecept run --debug

# configure notifications (email, IRC, campfire etc)
notifications:
